package lsf.FEII.model;

// Generated Oct 24, 2016 12:54:05 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * EjAttributesActive generated by hbm2java
 */
@Entity
@Table(name = "ej_attributes_active", catalog = "feiii_db")
public class EjAttributesActive implements java.io.Serializable {

	private EjAttributesActiveId id;
	private String DDtEnd;
	private String bhcInd;
	private String broadRegCd;
	private String chtrAuthCd;
	private String chtrTypeCd;
	private String fbo4c9Ind;
	private String fhcInd;
	private String funcReg;
	private String insurPriCd;
	private String mbrFhlbsInd;
	private String mbrFrsInd;
	private String secRptgStatus;
	private String estTypeCd;
	private String bnkTypeAnalysCd;
	private String DDtExistCmnc;
	private String DDtExistTerm;
	private String fiscYrendMmdd;
	private String DDtInsur;
	private String DDtOpen;
	private String fnclSubHolder;
	private String fnclSubInd;
	private String ibaGrndfthrInd;
	private String ibfInd;
	private String idRssdHdOff;
	private String mjrOwnMnrty;
	private String nmLgl;
	private String nmShort;
	private String nmSrchCd;
	private String orgTypeCd;
	private String reasonTermCd;
	private String cnsrvtrCd;
	private String entityType;
	private String authRegDistFrs;
	private String actPrimCd;
	private String city;
	private String cntryNm;
	private String idCusip;
	private String stateAbbrNm;
	private String placeCd;
	private String stateCd;
	private String stateHomeCd;
	private String streetLine1;
	private String streetLine2;
	private String zipCd;
	private String idThrift;
	private String idThriftHc;
	private String domesticInd;
	private String idAbaPrim;
	private String idFdicCert;
	private String idNcua;
	private String countyCd;
	private String distFrs;
	private String idOcc;
	private String cntryCd;
	private String dtEnd;
	private String dtExistCmnc;
	private String dtExistTerm;
	private String dtInsur;
	private String dtOpen;
	private String dtStart;
	private String idTax;
	private String provRegion;
	private String url;
	private String slhcInd;
	private String slhcTypeInd;
	private String primFedReg;
	private String stateIncCd;
	private String cntryIncCd;
	private String stateIncAbbrNm;
	private String cntryIncNm;

	public EjAttributesActive() {
	}

	public EjAttributesActive(EjAttributesActiveId id) {
		this.id = id;
	}

	public EjAttributesActive(EjAttributesActiveId id, String DDtEnd,
			String bhcInd, String broadRegCd, String chtrAuthCd,
			String chtrTypeCd, String fbo4c9Ind, String fhcInd, String funcReg,
			String insurPriCd, String mbrFhlbsInd, String mbrFrsInd,
			String secRptgStatus, String estTypeCd, String bnkTypeAnalysCd,
			String DDtExistCmnc, String DDtExistTerm, String fiscYrendMmdd,
			String DDtInsur, String DDtOpen, String fnclSubHolder,
			String fnclSubInd, String ibaGrndfthrInd, String ibfInd,
			String idRssdHdOff, String mjrOwnMnrty, String nmLgl,
			String nmShort, String nmSrchCd, String orgTypeCd,
			String reasonTermCd, String cnsrvtrCd, String entityType,
			String authRegDistFrs, String actPrimCd, String city,
			String cntryNm, String idCusip, String stateAbbrNm, String placeCd,
			String stateCd, String stateHomeCd, String streetLine1,
			String streetLine2, String zipCd, String idThrift,
			String idThriftHc, String domesticInd, String idAbaPrim,
			String idFdicCert, String idNcua, String countyCd, String distFrs,
			String idOcc, String cntryCd, String dtEnd, String dtExistCmnc,
			String dtExistTerm, String dtInsur, String dtOpen, String dtStart,
			String idTax, String provRegion, String url, String slhcInd,
			String slhcTypeInd, String primFedReg, String stateIncCd,
			String cntryIncCd, String stateIncAbbrNm, String cntryIncNm) {
		this.id = id;
		this.DDtEnd = DDtEnd;
		this.bhcInd = bhcInd;
		this.broadRegCd = broadRegCd;
		this.chtrAuthCd = chtrAuthCd;
		this.chtrTypeCd = chtrTypeCd;
		this.fbo4c9Ind = fbo4c9Ind;
		this.fhcInd = fhcInd;
		this.funcReg = funcReg;
		this.insurPriCd = insurPriCd;
		this.mbrFhlbsInd = mbrFhlbsInd;
		this.mbrFrsInd = mbrFrsInd;
		this.secRptgStatus = secRptgStatus;
		this.estTypeCd = estTypeCd;
		this.bnkTypeAnalysCd = bnkTypeAnalysCd;
		this.DDtExistCmnc = DDtExistCmnc;
		this.DDtExistTerm = DDtExistTerm;
		this.fiscYrendMmdd = fiscYrendMmdd;
		this.DDtInsur = DDtInsur;
		this.DDtOpen = DDtOpen;
		this.fnclSubHolder = fnclSubHolder;
		this.fnclSubInd = fnclSubInd;
		this.ibaGrndfthrInd = ibaGrndfthrInd;
		this.ibfInd = ibfInd;
		this.idRssdHdOff = idRssdHdOff;
		this.mjrOwnMnrty = mjrOwnMnrty;
		this.nmLgl = nmLgl;
		this.nmShort = nmShort;
		this.nmSrchCd = nmSrchCd;
		this.orgTypeCd = orgTypeCd;
		this.reasonTermCd = reasonTermCd;
		this.cnsrvtrCd = cnsrvtrCd;
		this.entityType = entityType;
		this.authRegDistFrs = authRegDistFrs;
		this.actPrimCd = actPrimCd;
		this.city = city;
		this.cntryNm = cntryNm;
		this.idCusip = idCusip;
		this.stateAbbrNm = stateAbbrNm;
		this.placeCd = placeCd;
		this.stateCd = stateCd;
		this.stateHomeCd = stateHomeCd;
		this.streetLine1 = streetLine1;
		this.streetLine2 = streetLine2;
		this.zipCd = zipCd;
		this.idThrift = idThrift;
		this.idThriftHc = idThriftHc;
		this.domesticInd = domesticInd;
		this.idAbaPrim = idAbaPrim;
		this.idFdicCert = idFdicCert;
		this.idNcua = idNcua;
		this.countyCd = countyCd;
		this.distFrs = distFrs;
		this.idOcc = idOcc;
		this.cntryCd = cntryCd;
		this.dtEnd = dtEnd;
		this.dtExistCmnc = dtExistCmnc;
		this.dtExistTerm = dtExistTerm;
		this.dtInsur = dtInsur;
		this.dtOpen = dtOpen;
		this.dtStart = dtStart;
		this.idTax = idTax;
		this.provRegion = provRegion;
		this.url = url;
		this.slhcInd = slhcInd;
		this.slhcTypeInd = slhcTypeInd;
		this.primFedReg = primFedReg;
		this.stateIncCd = stateIncCd;
		this.cntryIncCd = cntryIncCd;
		this.stateIncAbbrNm = stateIncAbbrNm;
		this.cntryIncNm = cntryIncNm;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idRssd", column = @Column(name = "ID_RSSD", nullable = false)),
			@AttributeOverride(name = "DDtStart", column = @Column(name = "D_DT_START", nullable = false)) })
	public EjAttributesActiveId getId() {
		return this.id;
	}

	public void setId(EjAttributesActiveId id) {
		this.id = id;
	}

	@Column(name = "D_DT_END")
	public String getDDtEnd() {
		return this.DDtEnd;
	}

	public void setDDtEnd(String DDtEnd) {
		this.DDtEnd = DDtEnd;
	}

	@Column(name = "BHC_IND")
	public String getBhcInd() {
		return this.bhcInd;
	}

	public void setBhcInd(String bhcInd) {
		this.bhcInd = bhcInd;
	}

	@Column(name = "BROAD_REG_CD")
	public String getBroadRegCd() {
		return this.broadRegCd;
	}

	public void setBroadRegCd(String broadRegCd) {
		this.broadRegCd = broadRegCd;
	}

	@Column(name = "CHTR_AUTH_CD")
	public String getChtrAuthCd() {
		return this.chtrAuthCd;
	}

	public void setChtrAuthCd(String chtrAuthCd) {
		this.chtrAuthCd = chtrAuthCd;
	}

	@Column(name = "CHTR_TYPE_CD")
	public String getChtrTypeCd() {
		return this.chtrTypeCd;
	}

	public void setChtrTypeCd(String chtrTypeCd) {
		this.chtrTypeCd = chtrTypeCd;
	}

	@Column(name = "FBO_4C9_IND")
	public String getFbo4c9Ind() {
		return this.fbo4c9Ind;
	}

	public void setFbo4c9Ind(String fbo4c9Ind) {
		this.fbo4c9Ind = fbo4c9Ind;
	}

	@Column(name = "FHC_IND")
	public String getFhcInd() {
		return this.fhcInd;
	}

	public void setFhcInd(String fhcInd) {
		this.fhcInd = fhcInd;
	}

	@Column(name = "FUNC_REG")
	public String getFuncReg() {
		return this.funcReg;
	}

	public void setFuncReg(String funcReg) {
		this.funcReg = funcReg;
	}

	@Column(name = "INSUR_PRI_CD")
	public String getInsurPriCd() {
		return this.insurPriCd;
	}

	public void setInsurPriCd(String insurPriCd) {
		this.insurPriCd = insurPriCd;
	}

	@Column(name = "MBR_FHLBS_IND")
	public String getMbrFhlbsInd() {
		return this.mbrFhlbsInd;
	}

	public void setMbrFhlbsInd(String mbrFhlbsInd) {
		this.mbrFhlbsInd = mbrFhlbsInd;
	}

	@Column(name = "MBR_FRS_IND")
	public String getMbrFrsInd() {
		return this.mbrFrsInd;
	}

	public void setMbrFrsInd(String mbrFrsInd) {
		this.mbrFrsInd = mbrFrsInd;
	}

	@Column(name = "SEC_RPTG_STATUS")
	public String getSecRptgStatus() {
		return this.secRptgStatus;
	}

	public void setSecRptgStatus(String secRptgStatus) {
		this.secRptgStatus = secRptgStatus;
	}

	@Column(name = "EST_TYPE_CD")
	public String getEstTypeCd() {
		return this.estTypeCd;
	}

	public void setEstTypeCd(String estTypeCd) {
		this.estTypeCd = estTypeCd;
	}

	@Column(name = "BNK_TYPE_ANALYS_CD")
	public String getBnkTypeAnalysCd() {
		return this.bnkTypeAnalysCd;
	}

	public void setBnkTypeAnalysCd(String bnkTypeAnalysCd) {
		this.bnkTypeAnalysCd = bnkTypeAnalysCd;
	}

	@Column(name = "D_DT_EXIST_CMNC")
	public String getDDtExistCmnc() {
		return this.DDtExistCmnc;
	}

	public void setDDtExistCmnc(String DDtExistCmnc) {
		this.DDtExistCmnc = DDtExistCmnc;
	}

	@Column(name = "D_DT_EXIST_TERM")
	public String getDDtExistTerm() {
		return this.DDtExistTerm;
	}

	public void setDDtExistTerm(String DDtExistTerm) {
		this.DDtExistTerm = DDtExistTerm;
	}

	@Column(name = "FISC_YREND_MMDD")
	public String getFiscYrendMmdd() {
		return this.fiscYrendMmdd;
	}

	public void setFiscYrendMmdd(String fiscYrendMmdd) {
		this.fiscYrendMmdd = fiscYrendMmdd;
	}

	@Column(name = "D_DT_INSUR")
	public String getDDtInsur() {
		return this.DDtInsur;
	}

	public void setDDtInsur(String DDtInsur) {
		this.DDtInsur = DDtInsur;
	}

	@Column(name = "D_DT_OPEN")
	public String getDDtOpen() {
		return this.DDtOpen;
	}

	public void setDDtOpen(String DDtOpen) {
		this.DDtOpen = DDtOpen;
	}

	@Column(name = "FNCL_SUB_HOLDER")
	public String getFnclSubHolder() {
		return this.fnclSubHolder;
	}

	public void setFnclSubHolder(String fnclSubHolder) {
		this.fnclSubHolder = fnclSubHolder;
	}

	@Column(name = "FNCL_SUB_IND")
	public String getFnclSubInd() {
		return this.fnclSubInd;
	}

	public void setFnclSubInd(String fnclSubInd) {
		this.fnclSubInd = fnclSubInd;
	}

	@Column(name = "IBA_GRNDFTHR_IND")
	public String getIbaGrndfthrInd() {
		return this.ibaGrndfthrInd;
	}

	public void setIbaGrndfthrInd(String ibaGrndfthrInd) {
		this.ibaGrndfthrInd = ibaGrndfthrInd;
	}

	@Column(name = "IBF_IND")
	public String getIbfInd() {
		return this.ibfInd;
	}

	public void setIbfInd(String ibfInd) {
		this.ibfInd = ibfInd;
	}

	@Column(name = "ID_RSSD_HD_OFF")
	public String getIdRssdHdOff() {
		return this.idRssdHdOff;
	}

	public void setIdRssdHdOff(String idRssdHdOff) {
		this.idRssdHdOff = idRssdHdOff;
	}

	@Column(name = "MJR_OWN_MNRTY")
	public String getMjrOwnMnrty() {
		return this.mjrOwnMnrty;
	}

	public void setMjrOwnMnrty(String mjrOwnMnrty) {
		this.mjrOwnMnrty = mjrOwnMnrty;
	}

	@Column(name = "NM_LGL")
	public String getNmLgl() {
		return this.nmLgl;
	}

	public void setNmLgl(String nmLgl) {
		this.nmLgl = nmLgl;
	}

	@Column(name = "NM_SHORT")
	public String getNmShort() {
		return this.nmShort;
	}

	public void setNmShort(String nmShort) {
		this.nmShort = nmShort;
	}

	@Column(name = "NM_SRCH_CD")
	public String getNmSrchCd() {
		return this.nmSrchCd;
	}

	public void setNmSrchCd(String nmSrchCd) {
		this.nmSrchCd = nmSrchCd;
	}

	@Column(name = "ORG_TYPE_CD")
	public String getOrgTypeCd() {
		return this.orgTypeCd;
	}

	public void setOrgTypeCd(String orgTypeCd) {
		this.orgTypeCd = orgTypeCd;
	}

	@Column(name = "REASON_TERM_CD")
	public String getReasonTermCd() {
		return this.reasonTermCd;
	}

	public void setReasonTermCd(String reasonTermCd) {
		this.reasonTermCd = reasonTermCd;
	}

	@Column(name = "CNSRVTR_CD")
	public String getCnsrvtrCd() {
		return this.cnsrvtrCd;
	}

	public void setCnsrvtrCd(String cnsrvtrCd) {
		this.cnsrvtrCd = cnsrvtrCd;
	}

	@Column(name = "ENTITY_TYPE")
	public String getEntityType() {
		return this.entityType;
	}

	public void setEntityType(String entityType) {
		this.entityType = entityType;
	}

	@Column(name = "AUTH_REG_DIST_FRS")
	public String getAuthRegDistFrs() {
		return this.authRegDistFrs;
	}

	public void setAuthRegDistFrs(String authRegDistFrs) {
		this.authRegDistFrs = authRegDistFrs;
	}

	@Column(name = "ACT_PRIM_CD")
	public String getActPrimCd() {
		return this.actPrimCd;
	}

	public void setActPrimCd(String actPrimCd) {
		this.actPrimCd = actPrimCd;
	}

	@Column(name = "CITY")
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "CNTRY_NM")
	public String getCntryNm() {
		return this.cntryNm;
	}

	public void setCntryNm(String cntryNm) {
		this.cntryNm = cntryNm;
	}

	@Column(name = "ID_CUSIP")
	public String getIdCusip() {
		return this.idCusip;
	}

	public void setIdCusip(String idCusip) {
		this.idCusip = idCusip;
	}

	@Column(name = "STATE_ABBR_NM")
	public String getStateAbbrNm() {
		return this.stateAbbrNm;
	}

	public void setStateAbbrNm(String stateAbbrNm) {
		this.stateAbbrNm = stateAbbrNm;
	}

	@Column(name = "PLACE_CD")
	public String getPlaceCd() {
		return this.placeCd;
	}

	public void setPlaceCd(String placeCd) {
		this.placeCd = placeCd;
	}

	@Column(name = "STATE_CD")
	public String getStateCd() {
		return this.stateCd;
	}

	public void setStateCd(String stateCd) {
		this.stateCd = stateCd;
	}

	@Column(name = "STATE_HOME_CD")
	public String getStateHomeCd() {
		return this.stateHomeCd;
	}

	public void setStateHomeCd(String stateHomeCd) {
		this.stateHomeCd = stateHomeCd;
	}

	@Column(name = "STREET_LINE1")
	public String getStreetLine1() {
		return this.streetLine1;
	}

	public void setStreetLine1(String streetLine1) {
		this.streetLine1 = streetLine1;
	}

	@Column(name = "STREET_LINE2")
	public String getStreetLine2() {
		return this.streetLine2;
	}

	public void setStreetLine2(String streetLine2) {
		this.streetLine2 = streetLine2;
	}

	@Column(name = "ZIP_CD")
	public String getZipCd() {
		return this.zipCd;
	}

	public void setZipCd(String zipCd) {
		this.zipCd = zipCd;
	}

	@Column(name = "ID_THRIFT")
	public String getIdThrift() {
		return this.idThrift;
	}

	public void setIdThrift(String idThrift) {
		this.idThrift = idThrift;
	}

	@Column(name = "ID_THRIFT_HC")
	public String getIdThriftHc() {
		return this.idThriftHc;
	}

	public void setIdThriftHc(String idThriftHc) {
		this.idThriftHc = idThriftHc;
	}

	@Column(name = "DOMESTIC_IND")
	public String getDomesticInd() {
		return this.domesticInd;
	}

	public void setDomesticInd(String domesticInd) {
		this.domesticInd = domesticInd;
	}

	@Column(name = "ID_ABA_PRIM")
	public String getIdAbaPrim() {
		return this.idAbaPrim;
	}

	public void setIdAbaPrim(String idAbaPrim) {
		this.idAbaPrim = idAbaPrim;
	}

	@Column(name = "ID_FDIC_CERT")
	public String getIdFdicCert() {
		return this.idFdicCert;
	}

	public void setIdFdicCert(String idFdicCert) {
		this.idFdicCert = idFdicCert;
	}

	@Column(name = "ID_NCUA")
	public String getIdNcua() {
		return this.idNcua;
	}

	public void setIdNcua(String idNcua) {
		this.idNcua = idNcua;
	}

	@Column(name = "COUNTY_CD")
	public String getCountyCd() {
		return this.countyCd;
	}

	public void setCountyCd(String countyCd) {
		this.countyCd = countyCd;
	}

	@Column(name = "DIST_FRS")
	public String getDistFrs() {
		return this.distFrs;
	}

	public void setDistFrs(String distFrs) {
		this.distFrs = distFrs;
	}

	@Column(name = "ID_OCC")
	public String getIdOcc() {
		return this.idOcc;
	}

	public void setIdOcc(String idOcc) {
		this.idOcc = idOcc;
	}

	@Column(name = "CNTRY_CD")
	public String getCntryCd() {
		return this.cntryCd;
	}

	public void setCntryCd(String cntryCd) {
		this.cntryCd = cntryCd;
	}

	@Column(name = "DT_END")
	public String getDtEnd() {
		return this.dtEnd;
	}

	public void setDtEnd(String dtEnd) {
		this.dtEnd = dtEnd;
	}

	@Column(name = "DT_EXIST_CMNC")
	public String getDtExistCmnc() {
		return this.dtExistCmnc;
	}

	public void setDtExistCmnc(String dtExistCmnc) {
		this.dtExistCmnc = dtExistCmnc;
	}

	@Column(name = "DT_EXIST_TERM")
	public String getDtExistTerm() {
		return this.dtExistTerm;
	}

	public void setDtExistTerm(String dtExistTerm) {
		this.dtExistTerm = dtExistTerm;
	}

	@Column(name = "DT_INSUR")
	public String getDtInsur() {
		return this.dtInsur;
	}

	public void setDtInsur(String dtInsur) {
		this.dtInsur = dtInsur;
	}

	@Column(name = "DT_OPEN")
	public String getDtOpen() {
		return this.dtOpen;
	}

	public void setDtOpen(String dtOpen) {
		this.dtOpen = dtOpen;
	}

	@Column(name = "DT_START")
	public String getDtStart() {
		return this.dtStart;
	}

	public void setDtStart(String dtStart) {
		this.dtStart = dtStart;
	}

	@Column(name = "ID_TAX")
	public String getIdTax() {
		return this.idTax;
	}

	public void setIdTax(String idTax) {
		this.idTax = idTax;
	}

	@Column(name = "PROV_REGION")
	public String getProvRegion() {
		return this.provRegion;
	}

	public void setProvRegion(String provRegion) {
		this.provRegion = provRegion;
	}

	@Column(name = "URL")
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@Column(name = "SLHC_IND")
	public String getSlhcInd() {
		return this.slhcInd;
	}

	public void setSlhcInd(String slhcInd) {
		this.slhcInd = slhcInd;
	}

	@Column(name = "SLHC_TYPE_IND")
	public String getSlhcTypeInd() {
		return this.slhcTypeInd;
	}

	public void setSlhcTypeInd(String slhcTypeInd) {
		this.slhcTypeInd = slhcTypeInd;
	}

	@Column(name = "PRIM_FED_REG")
	public String getPrimFedReg() {
		return this.primFedReg;
	}

	public void setPrimFedReg(String primFedReg) {
		this.primFedReg = primFedReg;
	}

	@Column(name = "STATE_INC_CD")
	public String getStateIncCd() {
		return this.stateIncCd;
	}

	public void setStateIncCd(String stateIncCd) {
		this.stateIncCd = stateIncCd;
	}

	@Column(name = "CNTRY_INC_CD")
	public String getCntryIncCd() {
		return this.cntryIncCd;
	}

	public void setCntryIncCd(String cntryIncCd) {
		this.cntryIncCd = cntryIncCd;
	}

	@Column(name = "STATE_INC_ABBR_NM")
	public String getStateIncAbbrNm() {
		return this.stateIncAbbrNm;
	}

	public void setStateIncAbbrNm(String stateIncAbbrNm) {
		this.stateIncAbbrNm = stateIncAbbrNm;
	}

	@Column(name = "CNTRY_INC_NM")
	public String getCntryIncNm() {
		return this.cntryIncNm;
	}

	public void setCntryIncNm(String cntryIncNm) {
		this.cntryIncNm = cntryIncNm;
	}

}
