package lsf.FEII.model;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * EjTransformationsId generated by hbm2java
 */
@Embeddable
public class EjTransformationsId implements java.io.Serializable {

	private String idRssdPredecessor;
	private String idRssdSuccessor;
	private String DDtTrans;

	public EjTransformationsId() {
	}

	public EjTransformationsId(String idRssdPredecessor,
			String idRssdSuccessor, String DDtTrans) {
		this.idRssdPredecessor = idRssdPredecessor;
		this.idRssdSuccessor = idRssdSuccessor;
		this.DDtTrans = DDtTrans;
	}

	@Column(name = "ID_RSSD_PREDECESSOR", nullable = false)
	public String getIdRssdPredecessor() {
		return this.idRssdPredecessor;
	}

	public void setIdRssdPredecessor(String idRssdPredecessor) {
		this.idRssdPredecessor = idRssdPredecessor;
	}

	@Column(name = "ID_RSSD_SUCCESSOR", nullable = false)
	public String getIdRssdSuccessor() {
		return this.idRssdSuccessor;
	}

	public void setIdRssdSuccessor(String idRssdSuccessor) {
		this.idRssdSuccessor = idRssdSuccessor;
	}

	@Column(name = "D_DT_TRANS", nullable = false)
	public String getDDtTrans() {
		return this.DDtTrans;
	}

	public void setDDtTrans(String DDtTrans) {
		this.DDtTrans = DDtTrans;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof EjTransformationsId))
			return false;
		EjTransformationsId castOther = (EjTransformationsId) other;

		return ((this.getIdRssdPredecessor() == castOther
				.getIdRssdPredecessor()) || (this.getIdRssdPredecessor() != null
				&& castOther.getIdRssdPredecessor() != null && this
				.getIdRssdPredecessor()
				.equals(castOther.getIdRssdPredecessor())))
				&& ((this.getIdRssdSuccessor() == castOther
						.getIdRssdSuccessor()) || (this.getIdRssdSuccessor() != null
						&& castOther.getIdRssdSuccessor() != null && this
						.getIdRssdSuccessor().equals(
								castOther.getIdRssdSuccessor())))
				&& ((this.getDDtTrans() == castOther.getDDtTrans()) || (this
						.getDDtTrans() != null
						&& castOther.getDDtTrans() != null && this
						.getDDtTrans().equals(castOther.getDDtTrans())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getIdRssdPredecessor() == null ? 0 : this
						.getIdRssdPredecessor().hashCode());
		result = 37
				* result
				+ (getIdRssdSuccessor() == null ? 0 : this.getIdRssdSuccessor()
						.hashCode());
		result = 37 * result
				+ (getDDtTrans() == null ? 0 : this.getDDtTrans().hashCode());
		return result;
	}

}
