package lsf.FEII.model;
// Generated Oct 24, 2016 12:54:05 PM by Hibernate Tools 3.4.0.CR1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * S1FinancialEntities generated by hbm2java
 */
@Entity
@Table(name=" s1_financial_entities"
    ,catalog="feiii_db"
)
public class S1FinancialEntities  implements java.io.Serializable {


     private int rssid;
     private Integer rank;
     private String institutionName;
     private String location;
     private String totalAssets;

    public S1FinancialEntities() {
    }

	
    public S1FinancialEntities(int rssid) {
        this.rssid = rssid;
    }
    public S1FinancialEntities(int rssid, Integer rank, String institutionName, String location, String totalAssets) {
       this.rssid = rssid;
       this.rank = rank;
       this.institutionName = institutionName;
       this.location = location;
       this.totalAssets = totalAssets;
    }
   
     @Id 

    
    @Column(name="RSSID", unique=true, nullable=false)
    public int getRssid() {
        return this.rssid;
    }
    
    public void setRssid(int rssid) {
        this.rssid = rssid;
    }

    
    @Column(name="Rank")
    public Integer getRank() {
        return this.rank;
    }
    
    public void setRank(Integer rank) {
        this.rank = rank;
    }

    
    @Column(name="InstitutionName")
    public String getInstitutionName() {
        return this.institutionName;
    }
    
    public void setInstitutionName(String institutionName) {
        this.institutionName = institutionName;
    }

    
    @Column(name="Location")
    public String getLocation() {
        return this.location;
    }
    
    public void setLocation(String location) {
        this.location = location;
    }

    
    @Column(name="TotalAssets")
    public String getTotalAssets() {
        return this.totalAssets;
    }
    
    public void setTotalAssets(String totalAssets) {
        this.totalAssets = totalAssets;
    }




}


